### ISSUE TITLE
does not work with multiple editors on the same page

### ISSUE THREAD

**Issue by artknight** [lqez/summernote-ext-print#2]
always shows the content of the first editor.

**Comment by artknight** [comment]
I solved the issue by replacing the code on line 51 with 

```
var iframeWindowObj = self.$printframe[0].contentWindow? self.$printframe[0].contentWindow : self.$printframe[0].contentDocument.defaultView;
iframeWindowObj.focus();
iframeWindowObj.print();
```

**Comment by lqez** [comment]
Oh thanks. Could you make a pull request for this?

**Comment by lqez** [comment]
I would like to put your modification on codes directly. If you have any opinion on it, please leave your comment here. Thanks.

**Comment by artknight** [comment]
sure go ahead!

**Comment by lqez** [comment]
Oki — Doki —

**Comment by lqez** [comment]
https://github.com/lqez/summernote-ext-print/commit/e53ef55683f12966c7d9e46ff8621951fbe0c9b4

**Comment by lqez** [comment]
v0.1.6 was just released. Thanks!

**Comment by lqez** [comment]
I added you on [`CHANGES`](https://github.com/lqez/summernote-ext-print/blob/master/CHANGES)
