### ISSUE TITLE
blank space when containing iframes

### ISSUE THREAD

**Issue by Emidomenge** [lqez/summernote-ext-print#3]
Here the summernote content : 
![summernote_print](https://cloud.githubusercontent.com/assets/15636263/16195890/ddacdeae-36fb-11e6-8658-528fae1da02b.png)

And here the preview when I want to print : 

![summernote_print_frame](https://cloud.githubusercontent.com/assets/15636263/16195911/ec694144-36fb-11e6-8025-4f9e7c1ecf9a.png)

**Comment by lqez** [comment]
Yes, and fixed by https://github.com/lqez/summernote-ext-print/commit/622bcbad2f664a39afedbbcafeb6a4b2a52dc181
Thanks!
