### ISSUE TITLE
Printing to xps or pdf (cute pdf)

### ISSUE THREAD

**Issue by roboriaan** [lqez/summernote-ext-print#5]
Not a big issue. Printing to xps or pdf generates a blank file. Probably not within the scope of this project. Tnx. Great plugin btw!

**Comment by lqez** [comment]
I tested this on Chrome, but it works well (yes, just tested on my pc lol)
![screen shot 2016-08-23 at 6 50 49 pm](https://cloud.githubusercontent.com/assets/579366/17887696/9cb34fc0-6962-11e6-8c8c-339ffa1329c5.png)

**Comment by lqez** [comment]
So, @roboriaan, please leave your environment information here. (browsers, etc)
