### ISSUE TITLE
nothing shown on print to PDF

### ISSUE THREAD

**Issue by topo79** [lqez/summernote-ext-print#6]
HI I am using FF Q
summer note 0.8.10
windows 2016 64b svr
and this plugin

when I click print it opens the print dialog, I select print to pdf and I got a blank one. I have no options setup on this plugin. Please help!

**Comment by corsariovasco** [comment]
Same problem with Firefox browser.

**Comment by lqez** [comment]
I will try out on FireFox.

**Comment by lqez** [comment]
Fixed by https://github.com/lqez/summernote-ext-print/commit/44a40dbb4b0a27a637659dda02d5278a50cbbe67

**Comment by lqez** [comment]
Please use v0.1.7 or later, thanks.

**Comment by corsariovasco** [comment]
Thanks!!, Works for me.
