### ISSUE TITLE
Vanilla JS standalone for Summernote version

### ISSUE THREAD

**Issue by Teolone88** [lqez/summernote-ext-print#7]
Hi,

Would be possible to have the same for the standalone version of Summernote, rather than the bootstrap version (Conflict with my app), using:

**1)** src = "https://code.jquery.com/jquery-3.4.1.slim.min.js", integrity = "sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
**2)** href = "https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.css"
**3)** src = "https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js"

**Print)** src = "https://raw.githubusercontent.com/lqez/summernote-ext-print/master/summernote-ext-print.js"

**Comment by lqez** [comment]
Hi @Teolone88, I'm not sure which part could be a problem while using it within `lite` version of Summernote.
But I'll check it out. And it would be awesome if you could provide detailed information about what you're stuck on.
Thanks.

**Comment by Teolone88** [comment]
Hi Iqez, I have actually solved it.

I have realized that I had to call all the buttons, once I add one. At least in my case.

Thx a lot for the feature.

Best,

Teo
